### ISSUE TITLE
[QUESTION] Virstual machine installation

### ISSUE THREAD

**Issue by nicotravassos** [twilio/twilio-chat-console-webapp.js#11]
Dear @aleksandrsivanovs,

Would it be possible to run this example on a virtual machine and not make use of ngrok? If so could you kindly provide documentation on how run example on a Ubuntu VM?

**Comment by aleksandrsivanovs** [comment]
Hi!

In this example ngrok is only used for exposing the app to the web (and not only to localhost).
So, it's really not required by the Twilio Chat - we used it here because it's easy and achieves the goal (the goal was to be able to run the same app from different browsers on different machines and phones). 

so, any web-server which can host html/js will work here (not sure on details, though, as it might be tricky to setup the FCM then, tricky, but not undoable) :)

Aleksandrs

**Comment by nicotravassos** [comment]
Thanks @aleksandrsivanovs
